                    <?foreach($this->tbEdit->getTableData() as $row):?>
                    <tr>
                        <?foreach($this->tbEdit->getFields() as $field) if($field['isVisible']=='1'):?>
                        <?='<td style="border-bottom: 1px solid black; min-width:'.$field['width'].';">'?>
                            <?=$row[$field['name']]?>
                        </td>
                        <?endif;?>
                    </tr>
                    <?endforeach;?>