<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />  
<div class="box">
    <div class="box-header fixed">
        <h1>Направления в фирму</h1>
    </div>
    <table class="datatable head" style="position: absolute;width: 1520px;top: 41px;background: #F8F8F8;">
        <thead>
            <tr>
                <th style="width:12%" class="filtered" data-key="tsdate" data-sort="" data-int="true"><p style="display: block; position: absolute; width: 400px;">Дата начало: <input type="text" class="datepicker" name="date_start" size="6" />
            Дата окончание: <input type="text" class="datepicker" name="date_end" size="6"/></p></th>
        </tr>
        <tr>
            <th style="width:12%" class="sorting filtered" data-key="tsdate" data-sort="" data-int="true">Дата</th>
            <th style="width:14%" class="sorting" data-key="stat_inet_referrer_host" data-sort="" data-int="true">Тип</th>
            <th style="width:26%" class="sorting filtered" data-key="medical_product_name_name" data-sort="">
                Торговое наименование
        <div style="position: absolute; bottom: -3px; left: 0px; width: 100%; display: block;">
            <input name="medical_product_name_name" type="text" style="height: 17px;font-size: 12px;width: 100%;margin-bottom: 2px;">
        </div>
        </th>
        <th style="width:26%" class="sorting filtered" data-key="medical_product_name" data-sort="">
            Дозировка
        <div style="position: absolute; bottom: -3px; left: 0px; width: 100%;">
            <input name="medical_product_name" type="text" style="height: 17px;font-size: 12px;width: 100%;margin-bottom: 2px;">
        </div>
        </th>
        <th style="width:10%" class="sorting" data-key="answer_count" data-sort="" data-int="true">Количество направлений</th>
        </tr>
        </thead>
    </table>
    <table class="datatable scrolled" data-page="<?= $this->table_meta["page"] ?>" data-url="<?= $this->url(array("module" => "cabinet", "controller" => "reports", "action" => "directionsonfirm", "firm" => $this->firm_id, "json" => 1)) ?>">
        <tbody>
            <? if ($this->table) foreach ($this->table as $arRow): ?>
                    <tr>
                        <td style="width:12%"><?= $arRow['tsdate'] ?></td>
                        <td style="width:14%"><?= $arRow['stat_inet_referrer_host'] ?></td>
                        <td style="width:26%"><?= $arRow['medical_product_name_name'] ?></td>
                        <td style="width:26%"><?= $arRow['medical_product_name'] ?></td>
                        <td style="width:10%"><?= $arRow['answer_count'] ?></td>
                    </tr>
                <? endforeach; ?>
        </tbody>
    </table>
    <table class="datatable foot" style="position: absolute;width: 1520px;bottom: 41px;background: #F8F8F8;">
        <thead>
            <tr>
                <th style="width:12%">Итоги</th>
                <th style="width:14%"></th>
                <th style="width:26%"></th>
                <th style="width:26%"></th>
                <th style="width:10%" id="answer_count_sum"><?= $this->table_meta['cnt']['answer_count'] ?></th>
            </tr>
        </thead>
    </table>
    <div class="action_bar nomargin fixed">
        <div class="dataTables_info" id="str_cnt">Всего <i><?= $this->table_meta['cnt']['cnt'] ?></i> строк</div>
        <div class="strong dataTables_paginate red" id="load_data" style="display:none">Загрузка данных</div>
    </div>
</div>

<script id="datatableRowTemplate" type="text/x-jquery-tmpl">
    <tr>
        <td style="width:12%">${$data.tsdate}</td>
        <td style="width:14%">${$data.stat_inet_referrer_host}</td>
        <td style="width:26%">${$data.medical_product_name_name}</td>
        <td style="width:26%">${$data.medical_product_name}</td>
        <td style="width:10%">${$data.answer_count}</td>
    </tr>
</script>