
<form method="post">
    <p>
        <input type="text" id="username" name="username" placeholder="Username" class="{validate: {required: true}}" />
    </p>
    <p>
        <input type="password" id="password" name="password" placeholder="Password" class="{validate: {required: true}}" />
    </p>
    <button type="submit" class="button blue"><span class="glyph key"></span> Login</button>
</form>
<p> 
<a href="/cabinet/user/restore/" >Напомнить пароль </a>
</p>