<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle($this->noIndex?'Справмедика':'', Zend_View_Helper_Placeholder_Container_Abstract::PREPEND)
             ->setSeparator(': ')
        ?>
        <?= $this->headMeta()->appendName('keywords', 'meta keywords') ?>
        <?= $this->headLink()->appendStylesheet("/css/main.css") ?>
        <?= $this->headScript()->appendFile('/adriverCore2/adriver.core.2.js')
            ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js')?>
        <?= $this->headStyle() ?>
        <?=$this->domain_data["inet_domen_counter_code2"] ?>
        <?if($this->noIndex):?><meta name="robots" content="noindex" /><?endif?>
    </head>

    <body>
        <?=$this->domain_data["inet_domen_counter_code"] ?>
        <div id="div_main" style="max-width: 1260px; margin: 0px auto; text-align: left; min-height: 900px;">
            <div id="div_menu_top2" style="margin: 0px 5px; text-align: center; font-size: 12px; overflow: hidden; background-color: rgb(232, 233, 236); height: 17px; display: block; background-position: initial initial; background-repeat: initial initial;">
                <?foreach($this->head_menu as $sStr):?>
                    <?=$sStr['href']?>
                <?endforeach;?>
            </div>
            <table id="main1_table">
                <tr>
                    <td id="main1_table_r2c1" colspan="2"> 
                        <div id="top_header_div" style="display: block;">
                            <div>
                                <a class="a_black" style="text-decoration:underline;" href="http://003ms.ru">003ms.ru</a> - Справочная аптек и медицинских услуг <?=$this->domain_data['area_FullName2']?$this->domain_data['area_FullName2']:'России'?> 
                            </div>
                        </div>
                        <div id="navBar1" style="display: block;">
                            <ul>
                                <?foreach ($this->top_menu as $sStr):?>
                                    <?=$sStr["href"]?>
                                <? endforeach;?>
                            </ul>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td id="main1_table_r3c1">
                        <table id="main2_table">
                            <tr>
                                <?if(!$this->hide_left):?>
                                <td id="main2_table_col1">
                                    <div id="div_mpn2">
                                        <div class="hdr_block_main">
                                            <div class="hdr_block_head"> Товары и услуги </div>
                                            <div class="hdr_block_text">
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=1">Лекарственные средства</a></div>
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=33">Оборудование</a></div>
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=7">Медицинские услуги</a></div>
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=5">Врачи</a></div>
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=6">Лабораторные анализы</a></div>
                                                <div class="hdr_block_line"><a class="a_black" href="/price.aspx?mpg_c=11">Лечение заболеваний</a></div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <?endif?>
                                <td id="main2_table_col2">
                                    <div id="div_context">
                                        <?=$this->layout()->content ?> 
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <?if(!$this->hide_right):?>
                    <td id="main1_table_r3c2">
                        <?php echo $this->action('partners',
                                 'blocks',
                                 'main',
                                 array('host' => explode(':',$_SERVER["HTTP_HOST"])[0],'noajax' => '0')); ?>
                        <?php echo $this->action('recomendations',
                                 'blocks',
                                 'main',
                                 array('host' => explode(':',$_SERVER["HTTP_HOST"])[0], 'mp_id' => $this->mp['medical_product_name_id'], 'noajax' => '0')); ?>
                    </td>
                    <?endif?>
                </tr>
            </table>
        </div>
        <div style="text-align:center;">
            <div id="div_counter_code">
                <?=$this->domain_data["inet_domen_counter_logo"] ?>
                <a href="http://validator.w3.org/check?uri=referer" target="_blank">
                    <img src="http://validator.w3.org/images/valid_icons/valid-xhtml10-blue" alt="Valid HTML 4.01 Strict" height="31" width="88"></img>
                </a>

                <a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">
                    <img style="border:0;width:88px;height:31px"
                        src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
                        alt="Правильный CSS!" />
                </a>

                <br/>вопросы по поиску лекарств присылайте на farmspravka@mail.ru - <a href="mailto:farmspravka@mail.ru">farmspravka@mail.ru</a><br/>замечания и ошибки по работе сайта присылайте на 003_adm@mail.ru - <a href="mailto:003_adm@mail.ru">003_adm@mail.ru</a><br/>
            </div>
        </div>
    </body>

</html>