<br /><br />
<script>
    function scroll_main(){
        var scrolled = document.getElementById('test_tbedit').scrollLeft;
        document.getElementById('test_head').scrollLeft = scrolled;
    }
</script>
<div id="view-content">
        <div>
        <?= $this->tbEdit->getTableTitle() ?>
        </div>
    <div id="test_head"  style="max-width: 600px; overflow-x: hidden; overflow-y: hidden;">
        <table border="1px" cellpadding="5px" cellspacing="0px">
            <thead>
                <?foreach($this->tbEdit->getFields() as $field) if($field['isVisible']=='1'):?>
                <?='<th style="min-width:'.$field['width'].';">'?>
                    <?=$field['title']?>
                </th>
                <?endif;?>
            </thead>
        </table>
    </div>
    <div id="test_tbedit"  style="max-width: 600px; height:500px; overflow-x: auto; overflow-y: auto;" onscroll="scroll_main();">
            <table cellpadding="5px" cellspacing="0px">
                <tbody>
                    <?foreach($this->tbEdit->getTableData(1) as $row):?>
                    <tr>
                        <?$this->recCount = $row['str_cnt'];?>
                        <?foreach($this->tbEdit->getFields() as $field) if($field['isVisible']=='1'):?>
                        <?='<td style="border-bottom: 1px solid black; min-width:'.$field['width'].';">'?>
                            <?=$row[$field['name']]?>
                        </td>
                        <?endif;?>
                    </tr>
                    <?endforeach;?>
                </tbody>
            </table>
    </div>
    <div id="test_foot"  style="max-width: 600px; overflow-x: hidden; overflow-y: hidden;">
        <table cellpadding="5px" cellspacing="0px">
            <thead>
                <th>
                    <?='Всего записей - '.$this->recCount?>
                </th>
            </thead>
        </table>
    </div>
</div>