<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="viewport" content="user-scalable=no" />

        <title>СправМедика</title>

        <!-- Stylesheets -->
        <link rel="stylesheet" href="/spina/css/reset.css" />
        <link rel="stylesheet" href="/spina/css/icons.css" />
        <link rel="stylesheet" href="/spina/css/formalize.css" />
        <link rel="stylesheet" href="/spina/css/jqueryui.css" />
        <link rel="stylesheet" href="/spina/css/960.css" />
        <link rel="stylesheet" href="/spina/css/main.css" />
        <link rel="stylesheet" media="all and (orientation:portrait)" href="/spina/css/portrait.css" />
        <link rel="apple-touch-icon" href="apple-touch-icon-precomposed.png" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

        <!--[if lt IE 9]>
        <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body id="login">
        
        <div id="login_container">
            <div id="login_form">
                
                <?=$this->layout()->content ?> 
                
            </div>
        </div>

        <!-- JavaScript -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
        <script>!window.jQuery && document.write('<script src="//yandex.st/jquery/1.9.0/jquery.min.js"><\/script>')</script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
        <script>!window.jQuery.datepicker && document.write('<script src="//yandex.st/jquery-ui/1.9.2/jquery-ui.min.js"><\/script>')</script>
        <script src="/spina/js/jquery.pjax.js"></script>
        <script src="/spina/js/jquery.inputtags.min.js"></script>
        <script src="/spina/js/jquery.validate.js"></script>
        <script src="/spina/js/jquery.livequery.js"></script>
        <script src="/spina/js/jquery.metadata.js"></script>
        <script src="/spina/js/application.js"></script>
    </body>
</html>
