<html lang="ru">
    <head>

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="viewport" content="width=1024px, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <meta charset="UTF-8"></head>

    <body>
        
            <div>
                <?=$this->layout()->content ?> 
            </div>
        <!-- JavaScript -->
    </body>
</html>